version: '3.8'
services:
  api:
    build: .
    container_name: flask_api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "5000:5000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  redis:
    image: redis:7-alpine
    container_name: redis_backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
